---

- name: Install DBeaver CE.
  tags: packages,software,dbeaver
  community.general.flatpak:
    name: io.dbeaver.DBeaverCommunity
    state: present
  when:
    - ansible_distribution == 'Fedora'
    - dbeaver is defined
    - dbeaver == true
