---

- name: Install dconf editor.
  tags: packages,software,dconf_editor
  ansible.builtin.package:
    name: dconf-editor
    state: present
  when:
    - ansible_distribution == 'Fedora'
    - dconf_editor is defined
    - dconf_editor
