---

- name: Install discord.
  tags: packages,software,discord
  community.general.flatpak:
    name: com.discordapp.Discord
    state: present
  when:
    - ansible_distribution == 'Fedora'
    - discord is defined
    - discord
