---

- name: Install discord.
  tags: packages,software,discord
  community.general.flatpak:
    name: com.discordapp.Discord
    state: present
  when:
    - bitwarden is defined
    - bitwarden == true
