---

- name: Install media codecs.
  tags: packages,software,codecs
  ansible.builtin.dnf:
    name:
        - gstreamer1-plugins-bad-*
        - gstreamer1-plugins-good-*
        - gstreamer1-plugins-base
        - gstreamer1-plugin-openh264
        - gstreamer1-libav
    state: present
    exclude: gstreamer1-plugins-bad-free-devel
  when:
    - ansible_distribution == 'Fedora'
    - media_codecs is defined
    - media_codecs
