---

- name: Add repository for virtualbox.
  tags: system,packages,software,virtualbox
  ansible.builtin.yum_repository:
    name: virtualbox
    description: Fedora - VirtualBox
    baseurl: "http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch"
    file: virtualbox
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: "https://www.virtualbox.org/download/oracle_vbox.asc"
  when:
    - ansible_distribution == 'Fedora'
    - virtualbox is defined
    - virtualbox

- name: Install virtualbox.
  tags: packages,software,virtualbox
  ansible.builtin.package:
    name: VirtualBox
    state: present
  when:
    - ansible_distribution == 'Fedora'
    - virtualbox is defined
    - virtualbox
  notify: restart_virtualbox_service
