---

- name: Create git global configuration.
  tags: software,dot_file
  become_user: "{{ user_name }}"
  community.general.git_config:
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: user.name
      value: Peter Ocelka
    - name: user.email
      value: peter.ocelka@gmail.com
    - name: core.editor
      value: vim
    - name: init.defaultBranch
      value: main
