---

- name: Copy git commit template.
  tags: software,dot_file,git
  become_user: "{{ user_name }}"
  ansible.builtin.copy:
    dest: "{{ user_home }}/.git_commit_template"
    src: git_commit_template

- name: Create git global configuration.
  tags: software,dot_file,git
  become_user: "{{ user_name }}"
  community.general.git_config:
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: user.name
      value: Peter Ocelka
    - name: user.email
      value: peter.ocelka@gmail.com
    - name: core.editor
      value: vim
    - name: init.defaultBranch
      value: main
    - name: commit.template
      value: "{{ user_home }}/.git_commit_template"
