---

autofs_master_path: "/etc/auto.master"
autofs_htpc_path: "/etc/auto.htpc"

oracle_client_url: "214000"
oracle_client_zip: "21.4.0.0.0"
oracle_client_dir: "21_4"

# Due to the license conditions, SQL Developer has to be manually downloaded before installation.
oracle_developer: "{{ user_home }}/Downloads/sqldeveloper-21.4.1-349.1822.noarch.rpm"
