" Enable syntax highlighting
syntax on

" Display line numbers
set number

" Indentation settings
set shiftwidth=4
set tabstop=4
set expandtab

" Always display status line; even if only one window is displayed
set laststatus=2

" Better command line completion
set wildmenu

" Encoding
set encoding=utf-8

" Show 120 char line
set colorcolumn=80,120
"highlight ColorColumn guibg=#2d2d2d ctermbg=246

" Don't line-wrap
set nowrap
