---

- name: restart_autofs
  tags: autofs,system,system setup
  ansible.builtin.service:
    name: autofs
    state: restarted

- name: restart_virtualbox_service
  ansible.builtin.service:
    name: vboxdrv
    state: restarted
