---

- name: restart_autofs
  ansible.builtin.service:
    name: autofs
    state: restarted

- name: restart_virtualbox_service
  ansible.builtin.service:
    name: vboxdrv
    state: restarted

- name: rebuild_fonts_cache
  become: true
  ansible.builtin.shell: "fc-cache -v -f"
