---

# Enable custom repositories for additional software
- name: Enable flatpak repository.
  tags: system,setup,repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
    method: system
    state: present
  when:
    - ansible_distribution == 'Fedora'

- name: Import rpm fusion security keys.
  tags: base_system_setup,repository,rpm_fusion
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
    - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
  when:
    - ansible_distribution == 'Fedora'

- name: Enable rpm fusion repositories.
  tags: system,setup,repository
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: present
  loop:
    - name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  when:
    - ansible_distribution == 'Fedora'
