---

# Enable custom repositories for additional software
- name: Enable flatpack repository.
  tags: system,setup,repository
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: "https://flathub.org/repo/flathub.flatpakrepo"
    method: system
    state: present
  when:
    - ansible_distribution == 'Fedora'

- name: Enable rpm fussion repositories.
  tags: system,setup,repository
  ansible.builtin.dnf:
    name: "{{ item.name }}"
    state: present
    disable_gpg_check: true
  loop:
    - name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  when:
    - ansible_distribution == 'Fedora'
