---

- name: Install development packages.
  tags: system,setup,dev,development,packages,software
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - "{{ python_package }}"
    - "{{ python_pip_package }}"
    - "{{ python_virtualenv_package }}"
    - "{{ python_psutil_package }}"
    - "{{ python_ansible_lint }}"
    - pre-commit                              # for git repository pre-commit checks
    - ShellCheck
    - jq
    - podman-compose
